import 'src/components/ListWords/styles.css'

const ListWords = () => {
  return (
    <ul className="list">
      <li className="list-item">First</li>
      <li className="list-item">Second</li>
      <li className="list-item">Third</li>
      <li className="list-item">Fourth</li>
      <li className="list-item">Fifth</li>
      <li className="list-item">First</li>
      <li className="list-item">Second</li>
      <li className="list-item">Third</li>
      <li className="list-item">Fourth</li>
      <li className="list-item">Fifth</li>
      <li className="list-item">First</li>
      <li className="list-item">Second</li>
      <li className="list-item">Third</li>
      <li className="list-item">Fourth</li>
      <li className="list-item">Fifth</li>
      <li className="list-item">First</li>
      <li className="list-item">Second</li>
      <li className="list-item">Third</li>
      <li className="list-item">Fourth</li>
      <li className="list-item">Fifth</li>
      <li className="list-item">First</li>
      <li className="list-item">Second</li>
      <li className="list-item">Third</li>
      <li className="list-item">Fourth</li>
      <li className="list-item">Fifth</li>
      <li className="list-item">First</li>
      <li className="list-item">Second</li>
      <li className="list-item">Third</li>
      <li className="list-item">Fourth</li>
      <li className="list-item">Fifth</li>
      <li className="list-item">First</li>
      <li className="list-item">Second</li>
      <li className="list-item">Third</li>
      <li className="list-item">Fourth</li>
      <li className="list-item">Fifth</li>
      <li className="list-item">First</li>
      <li className="list-item">Second</li>
      <li className="list-item">Third</li>
      <li className="list-item">Fourth</li>
      <li className="list-item">Fifth</li>
      <li className="list-item">First</li>
      <li className="list-item">Second</li>
      <li className="list-item">Third</li>
      <li className="list-item">Fourth</li>
      <li className="list-item">Fifth</li>
      <li className="list-item">First</li>
      <li className="list-item">Second</li>
      <li className="list-item">Third</li>
      <li className="list-item">Fourth</li>
      <li className="list-item">Fifth</li>
      <li className="list-item">First</li>
      <li className="list-item">Second</li>
      <li className="list-item">Third</li>
      <li className="list-item">Fourth</li>
      <li className="list-item">Fifth</li>
      <li className="list-item">First</li>
      <li className="list-item">Second</li>
      <li className="list-item">Third</li>
      <li className="list-item">Fourth</li>
      <li className="list-item">Fifth</li>
      <li className="list-item">First</li>
      <li className="list-item">Second</li>
      <li className="list-item">Third</li>
      <li className="list-item">Fourth</li>
      <li className="list-item">Fifth</li>
      <li className="list-item">First</li>
      <li className="list-item">Second</li>
      <li className="list-item">Third</li>
      <li className="list-item">Fourth</li>
      <li className="list-item">Fifth</li>
      <li className="list-item">First</li>
      <li className="list-item">Second</li>
      <li className="list-item">Third</li>
      <li className="list-item">Fourth</li>
      <li className="list-item">Fifth</li>
      <li className="list-item">First</li>
      <li className="list-item">Second</li>
      <li className="list-item">Third</li>
      <li className="list-item">Fourth</li>
      <li className="list-item">Fifth</li>
    </ul>
  )
}

export default ListWords
